name: Build x64 (Release)

on: [push, pull_request, workflow_dispatch]

jobs:
  call-workflow-build:
    uses: ./.github/workflows/workflow-build-wtl-submodule.yml
    with:
      platform-arch: x64
      build-config: Release
